name: CI-CD Pipeline Develop

on:
  push:
    branches: [ "develop" ]    # develop 브랜치에 push 될 때만 실행

env:   # 모든 job에 적용
  APP_DIR: ${{ secrets.DEV_EC2_APP_DIR }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: build/libs/*.jar


  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app
          path: ./deploy     # JAR 파일 저장 경로

      - name: Copy jar to Dev EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DEV_EC2_HOST }}
          username: ${{ secrets.DEV_EC2_USER }}
          key: ${{ secrets.DEV_EC2_KEY }}
          source: "./deploy/*.jar"
          target: ${{ secrets.DEV_EC2_APP_DIR }}

      - name: Restart application on Dev EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.DEV_EC2_HOST }}
          username: ${{ secrets.DEV_EC2_USER }}
          key: ${{ secrets.DEV_EC2_KEY }}
          envs: APP_DIR
          script: |
            APP_DIR="${APP_DIR}"
            
            echo "Stopping previous application..."
            
            # 8080 포트 프로세스 종료
            PID=$(lsof -t -i:8080)
            if [ -n "$PID" ]; then
              echo "Killing old app: $PID"
              kill -9 $PID
            else
              echo "No existing app running"
            fi
  
            cd "$APP_DIR/deploy" || { echo "DEPLOY CD FAILED"; exit 1; }

            JAR_FILE=$(ls -t *.jar | grep -v plain | head -n 1)

            echo "Starting new application: $JAR_FILE"

            # 메모리 제한 -Xms128m -Xmx256m
            # 실행시 yml 연결
            nohup java -Xms128m -Xmx256m -jar "$APP_DIR/deploy/$JAR_FILE" --spring.config.location=file:$APP_DIR/application.yml > "$APP_DIR/app.log" 2>&1 &

